// Every Prisma model that carries an `academyId` column and a matching
// row-level-security policy (see the `academy_rls` migration) — i.e. every
// model except the shared/global RBAC catalog (`Role`, `Permission`,
// `RolePermission`), the tenant root itself (`Academy`), and any future
// platform-operator model that deliberately sits outside the tenant model.
//
// PrismaService uses this to decide which model delegates need their calls
// wrapped with a `SET LOCAL app.current_academy_id` step before running —
// see prisma.service.ts.
export const TENANT_SCOPED_MODELS = new Set<string>([
  'User',
  'PasswordResetToken',
  'UserRole',
  'Season',
  'AgeCategory',
  'Team',
  'TrainingGroup',
  'Player',
  'Guardian',
  'PlayerGuardian',
  'PlayerRegistration',
  'PlayerGroupAssignment',
  'FeeType',
  'FeeItem',
  'FeeTypeItem',
  'FeeStructure',
  'Invoice',
  'Payment',
  'PaymentAllocation',
  'FinancialAdjustment',
  'Coach',
  'CoachAssignment',
  'CoachQualification',
  'TrainingPlan',
  'TrainingActivity',
  'TrainingActivityMark',
  'TrainingApproval',
  'TrainingSession',
  'TrainingScheduleSlot',
  'PlayerOfTheWeek',
  'GalleryPhoto',
  'TrainingSessionActivity',
  'TrainingAttendance',
  'AssessmentTemplate',
  'AssessmentCriteria',
  'PlayerAssessment',
  'AssessmentRating',
  'CoachRemark',
  'Opponent',
  'Match',
  'MatchParticipation',
  'MatchPlayerAssessment',
  'CoachFeedback',
  'CoachFeedbackCriteria',
  'ParentIssue',
  'IssueMessage',
  'Product',
  'ProductImage',
  'ProductVariant',
  'MerchandiseOrder',
  'MerchandiseOrderItem',
  'Notification',
  'AuditLog',
  'Document',
  'ConfigurationSetting',
  'PublicInquiry',
]);
